apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-css-app
  namespace: tg	
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-css-app
      env: stage
  template:
    metadata:
      labels:
        app: html-css-app
        env: stage
    spec:
      containers:
      - name: html-css-container
        image: santoshairi/demo_project1:latest  # ✅ Corrected Image Name
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: html-css-service
  namespace: tg
spec:
  type: LoadBalancer
  selector:
    app: html-css-app
    env: stage
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
