apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-css-app
  namespace: tg	
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-css-app
      env: stage
  template:
    metadata:
      labels:
        app: html-css-app
    spec:
      containers:
      - name: html-css-container
        image: santoshairi/demo_project1/html-css-project:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: html-css-service
spec:
  type: LoadBalancer
  selector:
    app: html-css-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
